In [4]:
# 数据预处理：线性函数归一化与零均值归一化
    # 假设现在要分析一个人的身高与体重对健康的影响
        # 如下所示，训练数据集x中总共有5个样本，每个样本包含2个数值型特征分别为身高m，体重kg
        # 对这个5x2的矩阵分别进行线性函数归一化与零均值归一化

In [6]:
# 编造数据
import numpy as np
x = np.array([[1.73,68],[1.65,70],[1.78,65],[1.56,48],[1.68,50]])
x

array([[ 1.73, 68.  ],
       [ 1.65, 70.  ],
       [ 1.78, 65.  ],
       [ 1.56, 48.  ],
       [ 1.68, 50.  ]])

In [7]:
# 线性函数归一化
MMS_x = (x - np.min(x,axis=0)) / (np.max(x,axis=0) - np.min(x,axis=0))
MMS_x

array([[0.77272727, 0.90909091],
       [0.40909091, 1.        ],
       [1.        , 0.77272727],
       [0.        , 0.        ],
       [0.54545455, 0.09090909]])

In [8]:
# 零均值归一化
ZSN_x = (x - np.mean(x, axis=0)) / np.var(x, axis=0)
ZSN_x

array([[ 8.99280576e+00,  9.01109057e-02],
       [-5.39568345e+00,  1.13216266e-01],
       [ 1.79856115e+01,  5.54528651e-02],
       [-2.15827338e+01, -1.40942699e-01],
       [-3.99360800e-14, -1.17837338e-01]])