In [6]:
import numpy as np
x = np.array([2,4,5,3,-10,1])

In [7]:
np.argsort(x)

array([4, 5, 0, 3, 1, 2])

In [15]:
# argsort()函数是将x中的元素从小到大排列，提取其对应的index(索引号)
# 升序

In [14]:
np.argsort(-x)

array([2, 1, 3, 0, 5, 4])

In [ ]:
# 降序

In [9]:
arr = np.array([[0, 3], [2, 2]])

In [10]:
# 按列排序
np.argsort(arr, axis=0)

array([[0, 1],
       [1, 0]])

In [12]:
# 按行排序
np.argsort(arr, axis=1) 

array([[0, 1],
       [0, 1]])