In [1]:
import numpy as np

In [2]:
array_0 = np.zeros([3,5,6])

In [3]:
array_0

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [6]:
array_0.shape

(3, 5, 6)

In [7]:
array_0[0,:, :].shape

(5, 6)

In [8]:
array_0[1,:, :].shape

(5, 6)

In [9]:
array_0[2,:, :].shape

(5, 6)

In [10]:
array_0[0,:, :]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
array_0[:,0, :].shape

(3, 6)

In [12]:
array_0[:,1, :].shape

(3, 6)

In [13]:
array_0[:,2, :].shape

(3, 6)

In [14]:
array_0[:,0, :]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
array_0[:, :,0].shape

(3, 5)

In [16]:
array_0[:, :,0]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])