In [12]:
import numpy as np

In [13]:
# reshape（）是数组对象中的方法，用于改变数组的形状。
# 形状变化是基于数组元素不能改变的，变成的新形状中所包含的元素个数必须符合原来元素个数。如果数组元素发生变化的时候，就会报错

In [14]:
x = np.array([1,2,3,4,5,6,7,8])

In [15]:
y = x.reshape((2,4))
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
z = x.reshape((2,2,2))
z

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
# reshape函数生成的新数组和原始数组公用一个内存，也就是说，不管是改变新数组还是原始数组的元素，另一个数组也会随之改变

In [18]:
x[0] = 111
x

array([111,   2,   3,   4,   5,   6,   7,   8])

In [19]:
z

array([[[111,   2],
        [  3,   4]],

       [[  5,   6],
        [  7,   8]]])