In [2]:
# 官方解释
# numpy.stack(arrays, axis=0) 沿着新轴连接数组的序列
# axis参数指定新轴在结果尺寸中的索引。例如，如果axis=0，它将是第一个维度，如果axis=-1，它将是最后一个维度。
    # 参数： 数组：array_like的序列每个数组必须具有相同的形状。axis：int，可选输入数组沿其堆叠的结果数组中的轴。
    # 返回： 堆叠：ndarray堆叠数组比输入数组多一个维。

In [10]:
import numpy as np

In [11]:
a = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
b = np.array([[4, 5, 6], [4, 5, 6], [4, 5, 6]])

In [12]:
a.shape

(3, 3)

In [13]:
b.shape

(3, 3)

In [14]:
np.stack((a, b), axis=0).shape

(2, 3, 3)

In [15]:
np.stack((a, b), axis=1).shape

(3, 2, 3)

In [16]:
np.stack((a, b), axis=2).shape

(3, 3, 2)

In [17]:
# 有a，b两个数组，所有为2 
# axis等于几，2就出现在括号中的哪一个位置

In [18]:
np.stack((a, b), axis=1)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [19]:
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [20]:
b

array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [ ]:
# 从矩阵中元素坐标的角度分析
# a[0][0] = 1  b[0][0] = 4
# a[0][0][0]=1 b[0][1][0]=4
# 为什么a[0][0][0]=1中间是0，因为np.stack((a, b), axis=1)中，a在b的前面。
# 为什么b[0][1][0]=1中间是1，因为np.stack((a, b), axis=1)中，b在a的后面。